@tool
class_name Controls

# every button binding of the game and its tools, in one table. an entry is
#   {group, description, keys, mouse, joy, physical, builtin}
# keys are Key codes with KEY_MASK_* modifiers or'd in (KEY_MASK_CMD_OR_CTRL
# is Ctrl, Cmd on macOS), mouse are MouseButton indices, also with modifier
# masks or'd in, joy are JoyButton indices. physical entries bind the key
# position (WASD stays WASD on AZERTY), the rest bind the key label.
# builtin entries are Godot's own ui_* actions the menus lean on, listed
# here so the controls list is complete, never registered or written out.
#
# the table is the source of truth. register() adds what is missing to the
# InputMap at startup (GameSettings._ready), project.godot's [input] section
# is generated from it by GenerateInputMap.gd and a test checks the two
# agree, docs/CONTROLS.md is generated by GenerateControlsDoc.gd, and the
# pause menu and the F3 panel list describe(). scripts never test raw keys
# or buttons: game code asks event.is_action_pressed(Controls.X) or
# Input.is_action_pressed(Controls.X), the editors and plugins that also run
# inside the Godot editor (whose InputMap does not carry the game's actions)
# ask pressed / released / matches / held here, which fall back to the
# table, and editor buttons can take shortcut(action).
#
# modifiers when matching an event: Shift and Alt on the event are ignored
# unless the binding asks for them, Ctrl is not, so B and Ctrl+B are
# different bindings (Cmd counts as Ctrl)

# gameplay
const MOVE_LEFT := &"move_left"
const MOVE_RIGHT := &"move_right"
const MOVE_UP := &"move_up"
const MOVE_DOWN := &"move_down"
const DASH := &"dash"
const SHOOT := &"shoot"
const SPECIAL := &"special"
const SWAP_SPECIAL := &"swap_special"
# weapons
const WEAPON_1 := &"weapon_1"
const WEAPON_2 := &"weapon_2"
const WEAPON_3 := &"weapon_3"
const WEAPON_4 := &"weapon_4"
const WEAPON_5 := &"weapon_5"
const WEAPON_6 := &"weapon_6"
const WEAPONS: Array[StringName] = [WEAPON_1, WEAPON_2, WEAPON_3, WEAPON_4, WEAPON_5, WEAPON_6]
const NEXT_WEAPON := &"next_weapon"
# menus
const PAUSE := &"pause"
const UI_UP := &"ui_up"
const UI_DOWN := &"ui_down"
const UI_ACCEPT := &"ui_accept"
const UI_FOCUS_NEXT := &"ui_focus_next"
const UI_FOCUS_PREV := &"ui_focus_prev"
# debug
const EDITOR_TOGGLE := &"editor_toggle"
const DEBUG_PANEL := &"debug_panel"
const SPAWN_PANEL := &"spawn_panel"
const DEBUG_DIG := &"debug_dig"
const DEBUG_BURN := &"debug_burn"
# spawn panel
const SPAWN_GRAB := &"spawn_grab"
const SPAWN_ROTATE_LEFT := &"spawn_rotate_left"
const SPAWN_ROTATE_RIGHT := &"spawn_rotate_right"
const SPAWN_DRAG_CANCEL := &"spawn_drag_cancel"
const SPAWN_PANEL_CLOSE := &"spawn_panel_close"
# the sprite and multisprite canvases
const CANVAS_PRIMARY := &"canvas_primary"
const CANVAS_SECONDARY := &"canvas_secondary"
const CANVAS_PAN := &"canvas_pan"
const CANVAS_ZOOM_IN := &"canvas_zoom_in"
const CANVAS_ZOOM_OUT := &"canvas_zoom_out"
# sprite editor
const SPRITE_UNDO := &"sprite_undo"
const SPRITE_REDO := &"sprite_redo"
const SPRITE_SELECT_ALL := &"sprite_select_all"
const SPRITE_COPY := &"sprite_copy"
const SPRITE_CUT := &"sprite_cut"
const SPRITE_PASTE := &"sprite_paste"
const SPRITE_DUPLICATE := &"sprite_duplicate"
const SPRITE_FIT := &"sprite_fit"
const SPRITE_PENCIL := &"sprite_pencil"
const SPRITE_ERASER := &"sprite_eraser"
const SPRITE_FILL := &"sprite_fill"
const SPRITE_PICKER := &"sprite_picker"
const SPRITE_SELECT := &"sprite_select"
const SPRITE_MOVE := &"sprite_move"
const SPRITE_RECT := &"sprite_rect"
const SPRITE_LINE := &"sprite_line"
const SPRITE_SELECT_ADD := &"sprite_select_add"
const SPRITE_DESELECT := &"sprite_deselect"
const SPRITE_DELETE := &"sprite_delete"
const SPRITE_COMMIT := &"sprite_commit"
const SPRITE_ZOOM_IN := &"sprite_zoom_in"
const SPRITE_ZOOM_OUT := &"sprite_zoom_out"
const SPRITE_BRUSH_SMALLER := &"sprite_brush_smaller"
const SPRITE_BRUSH_BIGGER := &"sprite_brush_bigger"
const SPRITE_NUDGE_LEFT := &"sprite_nudge_left"
const SPRITE_NUDGE_RIGHT := &"sprite_nudge_right"
const SPRITE_NUDGE_UP := &"sprite_nudge_up"
const SPRITE_NUDGE_DOWN := &"sprite_nudge_down"
# multisprite editor
const MULTI_MOVE_MODE := &"multi_move_mode"
const MULTI_JOINT_MODE := &"multi_joint_mode"
const MULTI_ROTATE_LEFT := &"multi_rotate_left"
const MULTI_ROTATE_RIGHT := &"multi_rotate_right"
const MULTI_SET_HEAD := &"multi_set_head"
const MULTI_FIT := &"multi_fit"
const MULTI_DELETE := &"multi_delete"
const MULTI_DESELECT := &"multi_deselect"
# godot editor plugins
const PIPES_PAINT := &"pipes_paint"
const PIPES_ERASE := &"pipes_erase"
const PIPES_EDGE := &"pipes_edge"
const SCENARIO_DRAG := &"scenario_drag"
const DEBUG_DOCK_SWATCH := &"debug_dock_swatch"

const GROUPS: Array[String] = ["Gameplay", "Weapons", "Menus", "Debug", "Spawn panel", "Editor canvas", "Sprite editor", "Multisprite editor", "Editor plugins"]

const DEADZONE := 0.2

const CTRL := KEY_MASK_CMD_OR_CTRL
const SHIFT := KEY_MASK_SHIFT

const TABLE := {
	# Gameplay
	MOVE_LEFT: {"group": "Gameplay", "description": "Move left", "keys": [KEY_A, KEY_LEFT], "physical": true},
	MOVE_RIGHT: {"group": "Gameplay", "description": "Move right", "keys": [KEY_D, KEY_RIGHT], "physical": true},
	MOVE_UP: {"group": "Gameplay", "description": "Move up", "keys": [KEY_W, KEY_UP], "physical": true},
	MOVE_DOWN: {"group": "Gameplay", "description": "Move down", "keys": [KEY_S, KEY_DOWN], "physical": true},
	DASH: {"group": "Gameplay", "description": "Dash in the move direction", "keys": [KEY_SPACE, KEY_SHIFT], "physical": true},
	SHOOT: {"group": "Gameplay", "description": "Fire the current weapon", "mouse": [MOUSE_BUTTON_LEFT]},
	SPECIAL: {"group": "Gameplay", "description": "Hold the shield up", "mouse": [MOUSE_BUTTON_RIGHT]},
	SWAP_SPECIAL: {"group": "Gameplay", "description": "Swap the special (bound, nothing reads it yet)", "keys": [KEY_E], "physical": true},
	# Weapons
	WEAPON_1: {"group": "Weapons", "description": "Select weapon slot 1", "keys": [KEY_1], "physical": true},
	WEAPON_2: {"group": "Weapons", "description": "Select weapon slot 2", "keys": [KEY_2], "physical": true},
	WEAPON_3: {"group": "Weapons", "description": "Select weapon slot 3", "keys": [KEY_3], "physical": true},
	WEAPON_4: {"group": "Weapons", "description": "Select weapon slot 4", "keys": [KEY_4], "physical": true},
	WEAPON_5: {"group": "Weapons", "description": "Select weapon slot 5", "keys": [KEY_5], "physical": true},
	WEAPON_6: {"group": "Weapons", "description": "Select weapon slot 6", "keys": [KEY_6], "physical": true},
	NEXT_WEAPON: {"group": "Weapons", "description": "Cycle to the next weapon", "keys": [KEY_Q], "mouse": [MOUSE_BUTTON_WHEEL_DOWN], "physical": true},
	# Menus
	PAUSE: {"group": "Menus", "description": "Pause and resume the game", "keys": [KEY_ESCAPE], "joy": [JOY_BUTTON_START], "physical": true},
	UI_UP: {"group": "Menus", "description": "Menu cursor up (wraps), also the left stick", "keys": [KEY_UP], "joy": [JOY_BUTTON_DPAD_UP], "builtin": true},
	UI_DOWN: {"group": "Menus", "description": "Menu cursor down (wraps), also the left stick", "keys": [KEY_DOWN], "joy": [JOY_BUTTON_DPAD_DOWN], "builtin": true},
	UI_FOCUS_NEXT: {"group": "Menus", "description": "Menu cursor to the next button", "keys": [KEY_TAB], "builtin": true},
	UI_FOCUS_PREV: {"group": "Menus", "description": "Menu cursor to the previous button", "keys": [KEY_TAB | SHIFT], "builtin": true},
	UI_ACCEPT: {"group": "Menus", "description": "Press the button under the menu cursor", "keys": [KEY_ENTER, KEY_KP_ENTER, KEY_SPACE], "builtin": true},
	# Debug
	EDITOR_TOGGLE: {"group": "Debug", "description": "Open or close the sprite editor on the sprite under the cursor (the player when none)", "keys": [KEY_F2]},
	DEBUG_PANEL: {"group": "Debug", "description": "Open or close the debug panel (stats, pause and step, AI, controls)", "keys": [KEY_F3]},
	SPAWN_PANEL: {"group": "Debug", "description": "Open or close the spawn panel", "keys": [KEY_QUOTELEFT], "physical": true},
	DEBUG_DIG: {"group": "Debug", "description": "Cut a hole in the sprites under the cursor", "mouse": [MOUSE_BUTTON_LEFT]},
	DEBUG_BURN: {"group": "Debug", "description": "Set the cells under the cursor burning", "mouse": [MOUSE_BUTTON_RIGHT]},
	# Spawn panel
	SPAWN_GRAB: {"group": "Spawn panel", "description": "Press a card to spawn or drag it out, drag a dynamic sprite in the world", "mouse": [MOUSE_BUTTON_LEFT]},
	SPAWN_ROTATE_LEFT: {"group": "Spawn panel", "description": "Turn the dragged spawn left", "keys": [KEY_Q], "mouse": [MOUSE_BUTTON_WHEEL_UP]},
	SPAWN_ROTATE_RIGHT: {"group": "Spawn panel", "description": "Turn the dragged spawn right", "keys": [KEY_E], "mouse": [MOUSE_BUTTON_WHEEL_DOWN]},
	SPAWN_DRAG_CANCEL: {"group": "Spawn panel", "description": "Drop the drag without spawning", "keys": [KEY_ESCAPE]},
	SPAWN_PANEL_CLOSE: {"group": "Spawn panel", "description": "Close the spawn panel", "keys": [KEY_ESCAPE]},
	# Editor canvas
	CANVAS_PRIMARY: {"group": "Editor canvas", "description": "Use the tool, select or drag a sprite", "mouse": [MOUSE_BUTTON_LEFT]},
	CANVAS_SECONDARY: {"group": "Editor canvas", "description": "Use the tool with the second color, cancel a joint or selection", "mouse": [MOUSE_BUTTON_RIGHT]},
	CANVAS_PAN: {"group": "Editor canvas", "description": "Drag to pan the view, click to pick a color (sprite editor)", "mouse": [MOUSE_BUTTON_MIDDLE]},
	CANVAS_ZOOM_IN: {"group": "Editor canvas", "description": "Zoom in at the cursor", "mouse": [MOUSE_BUTTON_WHEEL_UP]},
	CANVAS_ZOOM_OUT: {"group": "Editor canvas", "description": "Zoom out at the cursor", "mouse": [MOUSE_BUTTON_WHEEL_DOWN]},
	# Sprite editor
	SPRITE_UNDO: {"group": "Sprite editor", "description": "Undo", "keys": [KEY_Z | CTRL]},
	SPRITE_REDO: {"group": "Sprite editor", "description": "Redo", "keys": [KEY_Y | CTRL, KEY_Z | CTRL | SHIFT]},
	SPRITE_SELECT_ALL: {"group": "Sprite editor", "description": "Select everything", "keys": [KEY_A | CTRL]},
	SPRITE_COPY: {"group": "Sprite editor", "description": "Copy the selection", "keys": [KEY_C | CTRL]},
	SPRITE_CUT: {"group": "Sprite editor", "description": "Cut the selection", "keys": [KEY_X | CTRL]},
	SPRITE_PASTE: {"group": "Sprite editor", "description": "Paste", "keys": [KEY_V | CTRL]},
	SPRITE_DUPLICATE: {"group": "Sprite editor", "description": "Duplicate the selection", "keys": [KEY_D | CTRL]},
	SPRITE_FIT: {"group": "Sprite editor", "description": "Fit the sprite to the view", "keys": [KEY_F, KEY_0 | CTRL]},
	SPRITE_PENCIL: {"group": "Sprite editor", "description": "Pencil tool", "keys": [KEY_B]},
	SPRITE_ERASER: {"group": "Sprite editor", "description": "Eraser tool", "keys": [KEY_E]},
	SPRITE_FILL: {"group": "Sprite editor", "description": "Fill tool", "keys": [KEY_G]},
	SPRITE_PICKER: {"group": "Sprite editor", "description": "Color picker tool", "keys": [KEY_I]},
	SPRITE_SELECT: {"group": "Sprite editor", "description": "Select tool", "keys": [KEY_M]},
	SPRITE_MOVE: {"group": "Sprite editor", "description": "Move tool", "keys": [KEY_V]},
	SPRITE_RECT: {"group": "Sprite editor", "description": "Rectangle tool", "keys": [KEY_R]},
	SPRITE_LINE: {"group": "Sprite editor", "description": "Line tool", "keys": [KEY_L]},
	SPRITE_SELECT_ADD: {"group": "Sprite editor", "description": "Hold while starting a selection to add to the current one", "keys": [KEY_SHIFT]},
	SPRITE_DESELECT: {"group": "Sprite editor", "description": "Drop the floating paste, else clear the selection", "keys": [KEY_ESCAPE]},
	SPRITE_DELETE: {"group": "Sprite editor", "description": "Drop the floating paste, else clear the selected cells", "keys": [KEY_DELETE, KEY_BACKSPACE]},
	SPRITE_COMMIT: {"group": "Sprite editor", "description": "Place the floating paste", "keys": [KEY_ENTER, KEY_KP_ENTER]},
	SPRITE_ZOOM_IN: {"group": "Sprite editor", "description": "Zoom in", "keys": [KEY_EQUAL, KEY_PLUS, KEY_KP_ADD]},
	SPRITE_ZOOM_OUT: {"group": "Sprite editor", "description": "Zoom out", "keys": [KEY_MINUS, KEY_KP_SUBTRACT]},
	SPRITE_BRUSH_SMALLER: {"group": "Sprite editor", "description": "Smaller brush", "keys": [KEY_BRACKETLEFT]},
	SPRITE_BRUSH_BIGGER: {"group": "Sprite editor", "description": "Bigger brush", "keys": [KEY_BRACKETRIGHT]},
	SPRITE_NUDGE_LEFT: {"group": "Sprite editor", "description": "Nudge the selection or paste left", "keys": [KEY_LEFT]},
	SPRITE_NUDGE_RIGHT: {"group": "Sprite editor", "description": "Nudge the selection or paste right", "keys": [KEY_RIGHT]},
	SPRITE_NUDGE_UP: {"group": "Sprite editor", "description": "Nudge the selection or paste up", "keys": [KEY_UP]},
	SPRITE_NUDGE_DOWN: {"group": "Sprite editor", "description": "Nudge the selection or paste down", "keys": [KEY_DOWN]},
	# Multisprite editor
	MULTI_MOVE_MODE: {"group": "Multisprite editor", "description": "Move mode", "keys": [KEY_V]},
	MULTI_JOINT_MODE: {"group": "Multisprite editor", "description": "Joint mode", "keys": [KEY_J]},
	MULTI_ROTATE_LEFT: {"group": "Multisprite editor", "description": "Turn the selected sprite left", "keys": [KEY_Q]},
	MULTI_ROTATE_RIGHT: {"group": "Multisprite editor", "description": "Turn the selected sprite right", "keys": [KEY_E]},
	MULTI_SET_HEAD: {"group": "Multisprite editor", "description": "Make the selected sprite the head (again to clear)", "keys": [KEY_H]},
	MULTI_FIT: {"group": "Multisprite editor", "description": "Fit the document to the view", "keys": [KEY_F]},
	MULTI_DELETE: {"group": "Multisprite editor", "description": "Remove the selected sprite", "keys": [KEY_DELETE, KEY_BACKSPACE]},
	MULTI_DESELECT: {"group": "Multisprite editor", "description": "Clear the selection and the pending joint", "keys": [KEY_ESCAPE]},
	# Editor plugins (inside the Godot editor)
	PIPES_PAINT: {"group": "Editor plugins", "description": "Pipes toolbar: paint with the brush", "mouse": [MOUSE_BUTTON_LEFT]},
	PIPES_ERASE: {"group": "Editor plugins", "description": "Pipes toolbar: erase (gauge brush: reset the gauge)", "mouse": [MOUSE_BUTTON_RIGHT]},
	PIPES_EDGE: {"group": "Editor plugins", "description": "Pipes toolbar, Pipe brush: hold to link or unlink the nearest edge instead of painting the cell", "keys": [KEY_SHIFT]},
	SCENARIO_DRAG: {"group": "Editor plugins", "description": "Scenario: drag a zone or placement handle", "mouse": [MOUSE_BUTTON_LEFT]},
	DEBUG_DOCK_SWATCH: {"group": "Editor plugins", "description": "Debug Draw dock: open the color picker of a swatch", "mouse": [MOUSE_BUTTON_LEFT]},
}

const KEY_NAMES := {
	"QuoteLeft": "`", "BracketLeft": "[", "BracketRight": "]", "Equal": "=", "Plus": "+", "Minus": "-",
	"Kp Add": "Keypad +", "Kp Subtract": "Keypad -", "Kp Enter": "Keypad Enter",
}
const MOUSE_NAMES := {
	MOUSE_BUTTON_LEFT: "Left mouse", MOUSE_BUTTON_RIGHT: "Right mouse", MOUSE_BUTTON_MIDDLE: "Middle mouse",
	MOUSE_BUTTON_WHEEL_UP: "Wheel up", MOUSE_BUTTON_WHEEL_DOWN: "Wheel down",
}
const JOY_NAMES := {
	JOY_BUTTON_A: "A", JOY_BUTTON_B: "B", JOY_BUTTON_X: "X", JOY_BUTTON_Y: "Y", JOY_BUTTON_BACK: "Back",
	JOY_BUTTON_START: "Start", JOY_BUTTON_DPAD_UP: "D-pad up", JOY_BUTTON_DPAD_DOWN: "D-pad down",
	JOY_BUTTON_DPAD_LEFT: "D-pad left", JOY_BUTTON_DPAD_RIGHT: "D-pad right",
}

const MODIFIER_MASK := KEY_MASK_SHIFT | KEY_MASK_ALT | KEY_MASK_META | KEY_MASK_CTRL | KEY_MASK_CMD_OR_CTRL

static var built := {}

# the actions this game owns, in table order (builtins left out)
static func actions() -> Array[StringName]:
	var out: Array[StringName] = []
	for action in TABLE:
		if not is_builtin(action):
			out.append(action)
	return out

static func is_builtin(action: StringName) -> bool:
	return TABLE.has(action) and TABLE[action].get("builtin", false)

static func entry(action: StringName) -> Dictionary:
	return TABLE.get(action, {})

# the table's bindings of an action as input events, built once
static func events(action: StringName) -> Array[InputEvent]:
	if built.has(action):
		return built[action]

	var out: Array[InputEvent] = []
	var data := entry(action)
	var physical: bool = data.get("physical", false)

	for code in data.get("keys", []):
		var key := InputEventKey.new()
		key.device = -1
		var bare: int = code & ~MODIFIER_MASK
		if physical:
			key.physical_keycode = bare
		else:
			key.keycode = bare
		apply_modifiers(key, code)
		out.append(key)

	for code in data.get("mouse", []):
		var button := InputEventMouseButton.new()
		button.device = -1
		button.button_index = code & ~MODIFIER_MASK
		apply_modifiers(button, code)
		out.append(button)

	for index in data.get("joy", []):
		var joy := InputEventJoypadButton.new()
		joy.device = -1
		joy.button_index = index
		out.append(joy)

	built[action] = out
	return out

static func apply_modifiers(event: InputEventWithModifiers, code: int) -> void:
	if code & KEY_MASK_CMD_OR_CTRL:
		event.command_or_control_autoremap = true
	else:
		event.ctrl_pressed = bool(code & KEY_MASK_CTRL)
		event.meta_pressed = bool(code & KEY_MASK_META)
	event.shift_pressed = bool(code & KEY_MASK_SHIFT)
	event.alt_pressed = bool(code & KEY_MASK_ALT)

# adds every table action missing from the InputMap, and every binding
# missing from an action. never removes, so a later rebind survives
static func register() -> void:
	for action in actions():
		if not InputMap.has_action(action):
			InputMap.add_action(action, DEADZONE)

		for event in events(action):
			if not has_event(InputMap.action_get_events(action), event):
				InputMap.action_add_event(action, event)

static func has_event(list: Array, event: InputEvent) -> bool:
	for other in list:
		if same_event(other, event):
			return true
	return false

# the same binding: same class, button or key (and whether physical) and
# the same modifiers
static func same_event(a: InputEvent, b: InputEvent) -> bool:
	if a.get_class() != b.get_class():
		return false

	if a is InputEventKey:
		if a.keycode != b.keycode or a.physical_keycode != b.physical_keycode:
			return false
	elif a is InputEventMouseButton or a is InputEventJoypadButton:
		if a.button_index != b.button_index:
			return false
	else:
		return a.is_match(b, true)

	if a is InputEventWithModifiers:
		return modifiers_of(a) == modifiers_of(b)
	return true

static func modifiers_of(event: InputEventWithModifiers) -> int:
	var mask := 0
	if event.ctrl_pressed or event.meta_pressed:
		mask |= KEY_MASK_CTRL
	if event.shift_pressed:
		mask |= KEY_MASK_SHIFT
	if event.alt_pressed:
		mask |= KEY_MASK_ALT
	return mask

# the bindings to test against: the InputMap's when the action is in it
# (the running game), the table's otherwise (inside the Godot editor)
static func bindings(action: StringName) -> Array:
	if InputMap.has_action(action):
		return InputMap.action_get_events(action)
	return events(action)

# the event is one of the action's bindings, pressed or released
static func matches(event: InputEvent, action: StringName) -> bool:
	for binding in bindings(action):
		if binding_matches(binding, event):
			return true
	return false

static func binding_matches(binding: InputEvent, event: InputEvent) -> bool:
	if binding is InputEventKey:
		if not (event is InputEventKey):
			return false
		if binding.physical_keycode != KEY_NONE:
			if binding.physical_keycode != event.physical_keycode:
				return false
		elif binding.keycode != event.keycode:
			return false
	elif binding is InputEventMouseButton:
		if not (event is InputEventMouseButton) or binding.button_index != event.button_index:
			return false
	elif binding is InputEventJoypadButton:
		return event is InputEventJoypadButton and binding.button_index == event.button_index
	else:
		return binding.is_match(event, false)

	# the binding's modifiers must be held, and Ctrl exactly as bound
	var want := modifiers_of(binding)
	var have := modifiers_of(event)
	return (want & have) == want and (want & KEY_MASK_CTRL) == (have & KEY_MASK_CTRL)

static func pressed(event: InputEvent, action: StringName, allow_echo := false) -> bool:
	if not event.is_pressed() or (event.is_echo() and not allow_echo):
		return false
	return matches(event, action)

static func released(event: InputEvent, action: StringName) -> bool:
	return not event.is_pressed() and matches(event, action)

# a binding of the action is down right now, read from the device state so
# it answers inside the Godot editor too
static func held(action: StringName) -> bool:
	for binding in bindings(action):
		if binding is InputEventKey:
			if binding.physical_keycode != KEY_NONE and Input.is_physical_key_pressed(binding.physical_keycode):
				return true
			if binding.keycode != KEY_NONE and Input.is_key_pressed(binding.keycode):
				return true
		elif binding is InputEventMouseButton:
			if Input.is_mouse_button_pressed(binding.button_index):
				return true
		elif binding is InputEventJoypadButton:
			for device in Input.get_connected_joypads():
				if Input.is_joy_button_pressed(device, binding.button_index):
					return true
	return false

# an action bound to a modifier key (Shift, Alt, Ctrl) is held on this
# event, read off the event so a synthesized one answers too, else the
# device state
static func modifier_held(event: InputEventWithModifiers, action: StringName) -> bool:
	for binding in bindings(action):
		if not (binding is InputEventKey):
			continue
		var code: int = binding.keycode if binding.keycode != KEY_NONE else binding.physical_keycode
		if (code == KEY_SHIFT and event.shift_pressed) or (code == KEY_ALT and event.alt_pressed) or (code == KEY_CTRL and (event.ctrl_pressed or event.meta_pressed)):
			return true
	return held(action)

# the mouse button index belongs to the action, for code that carries
# the index along (canvas signals, a stroke in progress)
static func has_mouse_button(action: StringName, index: int) -> bool:
	for binding in bindings(action):
		if binding is InputEventMouseButton and binding.button_index == index:
			return true
	return false

# a Shortcut of the action's key bindings, for buttons and menus inside the
# Godot editor where the game's InputMap is not loaded
static func shortcut(action: StringName) -> Shortcut:
	var out := Shortcut.new()
	var list: Array = []
	for event in events(action):
		if event is InputEventKey:
			list.append(event)
	out.events = list
	return out

# the list

static func key_text(code: int) -> String:
	var parts := OS.get_keycode_string(code).split("+")
	var last := parts[parts.size() - 1]
	if KEY_NAMES.has(last):
		parts[parts.size() - 1] = KEY_NAMES[last]
	return "+".join(parts)

static func key_texts(action: StringName) -> PackedStringArray:
	var data := entry(action)
	var out := PackedStringArray()
	for code in data.get("keys", []):
		out.append(key_text(code))
	return out

static func mouse_texts(action: StringName) -> PackedStringArray:
	var out := PackedStringArray()
	for code in entry(action).get("mouse", []):
		var text: String = MOUSE_NAMES.get(code & ~MODIFIER_MASK, "Mouse %d" % (code & ~MODIFIER_MASK))
		var mods: int = code & MODIFIER_MASK
		if mods:
			text = OS.get_keycode_string(mods).trim_suffix("+") + "+" + text
		out.append(text)
	return out

static func joy_texts(action: StringName) -> PackedStringArray:
	var out := PackedStringArray()
	for index in entry(action).get("joy", []):
		out.append("Pad " + JOY_NAMES.get(index, "button %d" % index))
	return out

# every action with its bindings as text, grouped in GROUPS order then
# table order: {action, group, description, keys, mouse, joy, physical, builtin}
static func describe() -> Array[Dictionary]:
	var out: Array[Dictionary] = []
	for group in GROUPS:
		for action in TABLE:
			var data: Dictionary = TABLE[action]
			if data["group"] != group:
				continue
			out.append({
				"action": action,
				"group": group,
				"description": data["description"],
				"keys": key_texts(action),
				"mouse": mouse_texts(action),
				"joy": joy_texts(action),
				"physical": data.get("physical", false),
				"builtin": data.get("builtin", false),
			})
	return out

# all of an action's bindings on one line, "A, Left, Pad Start"
static func bindings_text(row: Dictionary) -> String:
	var all := PackedStringArray()
	all.append_array(row["keys"])
	all.append_array(row["mouse"])
	all.append_array(row["joy"])
	return ", ".join(all)

# docs/CONTROLS.md
static func markdown() -> String:
	var lines := PackedStringArray()
	lines.append("# Controls")
	lines.append("")
	lines.append("Generated from `game/scripts/core/Controls.gd` by `game/scripts/core/GenerateControlsDoc.gd`, do not edit by hand.")
	lines.append("Keys marked with * are bound by position (the same place on any keyboard layout). Actions marked builtin are Godot's own ui_* actions.")
	lines.append("")
	var group := ""
	for row in describe():
		if row["group"] != group:
			if group != "":
				lines.append("")
			group = row["group"]
			lines.append("## " + group)
			lines.append("")
			lines.append("| Action | Keys | Mouse | Pad | Description |")
			lines.append("| --- | --- | --- | --- | --- |")
		var keys: PackedStringArray = row["keys"]
		var marked := PackedStringArray()
		for key in keys:
			marked.append(key + ("*" if row["physical"] else ""))
		var key_cell := ", ".join(marked)
		var name_cell := "`%s`%s" % [row["action"], " (builtin)" if row["builtin"] else ""]
		lines.append("| %s | %s | %s | %s | %s |" % [name_cell, cell(key_cell), cell(", ".join(row["mouse"])), cell(", ".join(row["joy"])), row["description"].replace("|", "\\|")])
	lines.append("")
	return "\n".join(lines)

static func cell(text: String) -> String:
	if text.is_empty():
		return ""
	return text.replace("|", "\\|").replace("`", "\\`")

# project.godot's [input] section, one entry per owned action
static func project_input_text() -> String:
	var lines := PackedStringArray()
	lines.append("[input]")
	lines.append("")
	for action in actions():
		# a plain Array, a typed one serializes as Array[InputEvent](...)
		var list: Array = []
		list.append_array(events(action))
		lines.append("%s=%s" % [action, var_to_str({"deadzone": DEADZONE, "events": list})])
	return "\n".join(lines) + "\n"
